#!/usr/bin/env bash
# Generate the recipes
while IFS= read -r recipe; do
	base="$(basename "$recipe")"
	dest="content/posts/${base%.yaml}.md"
	echo "$recipe -> $dest"
	~/go/bin/nom "$recipe" > "$dest"
done < <(find recipes -name *.yaml)
